# Generated by Django 5.2 on 2025-05-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ott', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ott',
            name='logo_url',
            field=models.URLField(blank=True, help_text='OTT 플랫폼의 로고 이미지 URL입니다 (선택사항)', verbose_name='로고 이미지 URL'),
        ),
        migrations.AlterField(
            model_name='ott',
            name='name',
            field=models.CharField(help_text='OTT 플랫폼 이름입니다. 예: Netflix, Watcha, Disney+', max_length=50, verbose_name='플랫폼 이름'),
        ),
    ]
