# Generated by Django 5.2 on 2025-05-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ott', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('ott_services', models.ManyToManyField(related_name='movies', to='ott.ott')),
            ],
        ),
    ]
