# Generated by Django 5.2 on 2025-05-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('ott', '0002_alter_ott_logo_url_alter_ott_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='average_rating_cache',
            field=models.FloatField(default=0.0, help_text='DB에 저장된 평균 평점 (성능 개선용)', verbose_name='평점 평균 캐시'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(help_text='영화의 줄거리 또는 개요를 입력합니다.', verbose_name='영화 설명'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='ott_services',
            field=models.ManyToManyField(related_name='movies', to='ott.ott', verbose_name='제공 OTT'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(help_text='영화의 공식 개봉일입니다.', verbose_name='개봉일'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='포스터나 썸네일 이미지의 URL입니다. (선택사항)', null=True, verbose_name='썸네일 이미지'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(help_text='영화의 제목입니다.', max_length=255, verbose_name='영화 제목'),
        ),
    ]
