# Generated by Django 5.2 on 2025-05-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ott', '0002_alter_ott_logo_url_alter_ott_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribed_ott',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='ott.ott', verbose_name='구독 중인 OTT'),
        ),
    ]
